[build]
  publish = "public"
  command = "./scripts/build.sh"

[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "development"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "development"

# Site redirects
[[redirects]]
  from = "/docs/build/*"
  to = "/docs/build"
  status = 301

